config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get '/tasks/:id', to: 'tasks#show', as: 'task'

  get '/tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy', as: 'task_delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task_info = task_params
    task_info[:completed] == "1" ? task_info[:completed] = true : task_info[:completed] = false
    @task = Task.find(params[:id])
    @task.update(task_info)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit task</h2>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.label :completed, "Completed" %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class="container p-2 col-6">
  <h2 class='my-5'>My tasks</h2>

  <div class="mb-3">
    <% @tasks.each do |task| %>
      <div class="d-flex justify-content-between w-100 align-item-center p-2  border rounded border-primary">
        <%= link_to task_path(task) do %>
          <div class='flex-fill'>
            <input type="checkbox"  class='mx-2' <%= 'checked' if task.completed == true%>>
            <%= task.title %>
          </div>
        <% end %>
        <%= link_to task_delete_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash mx-2"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="text-center">
    <%= link_to tasks_new_path do %>
      <button class="btn btn-primary">Create a new task</button>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<h2>Create a new tasks</h2>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div class="container p-2 col-6">
  <div class="d-inline-flex align-item-center mb-2">
    <h2><%= @task.title %></h2>
    <div class="m-2">
      <%= link_to task_edit_path do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
    </div>
  </div>

  <div class="border rounded border-primary m-1 p-1 mb-2 w-100">
    <p class='m-0'><%= @task.details %></p>
  </div>


  <div class="d-inline-flex align-item-center mb-2">
    <input type="checkbox" <%= 'checked' if @task.completed == true%>>
    <p style="margin: 0;">This task is completed</p>
  </div>

  <div class="text-center">
    <%= link_to tasks_path do %>
      <button class="btn btn-primary">Back</button>
    <% end %>
  </div>
</div>